language: python
python:
        - "2.7"
install: 
        - python setup.py install
        - pip install coveralls
script: nosetests  --with-coverage --cover-package=ftorrents 
after_success:
        coveralls
